// ==SE_module==
// name: motivation_toast
// displayName: Motivation Toast
// description: A Script that shows a random motivation quote toast on the startup of Snapchat.
// version: 1.0
// author: Suryadip Sarkar
// credits: Gabriel Modz & Jacob Thomas & Jimothy
// ==/SE_module==

var networking = require("networking");
var messaging = require("messaging");
var config = require("config");
var im = require("interface-manager");
var ipc = require("ipc");
var javaInterfaces = require("java-interfaces");
var hooker = require("hooker");
var events = require("events");

var settingsContext = {
        events: [],
};

var quotes = [
    "Believe you can and you're halfway there.",
    "Don't watch the clock; do what it does. Keep going.",
    "You are never too old to set another goal or to dream a new dream.",
    "It always seems impossible until it's done.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only way to do great work is to love what you do.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Act as if what you do makes a difference. It does.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Your time is limited, don't waste it living someone else's life.",
    "The best way to predict the future is to create it.",
    "You are enough just as you are.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Start where you are. Use what you have. Do what you can.",
    "Your life does not get better by chance, it gets better by change.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream big and dare to fail.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The purpose of our lives is to be happy.",
    "Don't let yesterday take up too much of today.",
    "Life is what happens when you're busy making other plans.",
    "You only live once, but if you do it right, once is enough.",
    "Never let the fear of striking out keep you from playing the game.",
    "Money and success don't change people; they merely amplify what is already there.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Not how long, but how well you have lived is the main thing.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
    "In order to write about life first you must live it.",
    "The big lesson in life, baby, is never be scared of anyone or anything.",
    "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
    "Life is not a problem to be solved, but a reality to be experienced.",
    "The unexamined life is not worth living.",
    "Turn your wounds into wisdom.",
    "The way I see it, if you want the rainbow, you gotta put up with the rain.",
    "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
    "Don't settle for what life gives you; make life better and build something.",
    "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
    "I like criticism. It makes you strong.",
    "You never really learn much from hearing yourself speak.",
    "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.",
    "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.",
    "Live for each second without hesitation.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Life is really simple, but men insist on making it complicated.",
    "Life is a succession of lessons which must be lived to be understood.",
    "My mama always said, life is like a box of chocolates. You never know what you're gonna get.",
    "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.",
    "When we do the best we can, we never know what miracle is wrought in our life or the life of another.",
    "The healthiest response to life is joy.",
    "Life is short, and it's up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
    "All life is an experiment. The more experiments you make, the better.",
    "You get in life what you have the courage to ask for.",
    "The great pleasure in life is doing what people say you cannot do.",
    "I tell you, in this world being a little crazy helps to keep you sane.",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
    "Your life does not get better by chance, it gets better by change.",
    "Don't cry because it's over, smile because it happened.",
    "I have found that if you love life, life will love you back.",
    "Don't take life too seriously. You'll never get out of it alive.",
    "We know what we are, but know not what we may be.",
    "Life is a song - sing it. Life is a game - play it. Life is a challenge - meet it. Life is a dream - realize it. Life is a sacrifice - offer it. Life is love - enjoy it.",
    "Love the life you live. Live the life you love.",
    "You only live once, but if you do it right, once is enough.",
    "Life is made up of years that mean nothing and moments that mean it all.",
    "Sometimes the questions are complicated and the answers are simple.",
    "Life is ten percent what happens to us and ninety percent how we respond to it.",
    "The good life is one inspired by love and guided by knowledge.",
    "Life is about making an impact, not making an income.",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
    "An unexamined life is not worth living.",
    "Live life to the fullest, and focus on the positive.",
    "Life is either a great adventure or nothing.",
    "Our life is what our thoughts make it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The mind is everything. What you think you become.",
    "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.",
    "You have to be able to accept failure to get better.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Life is a balance of holding on and letting go.",
    "If you're going through hell, keep going.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is short, and it is up to you to make it sweet.",
    "Keep calm and carry on.",
    "Maybe that's what life is... a wink of the eye and winking stars.",
    "Life is ten percent what happens to you and ninety percent how you respond to it.",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Believe that life is worth living and your belief will help create the fact.",
    "The only impossible journey is the one you never begin.",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit.",
    "You cannot control everything that happens to you; you can only control the way you respond to what happens. In your response is your power.",
    "Our lives begin to end the day we become silent about things that matter.",
    "In three words I can sum up everything I've learned about life: It goes on.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "The best way to get started is to quit talking and begin doing.",
    "Don't let what you cannot do interfere with what you can do.",
    "Dream as if you'll live forever, live as if you'll die today.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Life is either a daring adventure or nothing at all.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Life shrinks or expands in proportion to one's courage.",
    "You must be the change you wish to see in the world.",
    "The best revenge is massive success.",
    "Dream big and dare to fail.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life would be tragic if it weren't funny.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "Do not let making a living prevent you from making a life.",
    "Life is a flower of which love is the honey.",
    "Keep your eyes on the stars and your feet on the ground.",
    "The only way to have a friend is to be one.",
    "It is not length of life, but depth of life.",
    "Life is made of ever so many partings welded together.",
    "Life's tragedy is that we get old too soon and wise too late.",
    "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Life is trying things to see if they work.",
    "Life is what we make it, always has been, always will be.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "Life is too important to be taken seriously.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more I realize the impact of attitude on life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life doesn't require that we be the best, only that we try our best.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "Life is short, and it is up to you to make it sweet.",
    "A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing.",
    "The chief danger in life is that you may take too many precautions.",
    "Life is an opportunity, benefit from it. Life is beauty, admire it. Life is a dream, realize it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "When you cease to dream you cease to live.",
    "You are never too old to set another goal or to dream a new dream.",
    "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.",
    "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
];

function getRandomQuote() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}

function createManagerToolBoxUI() {
    
    settingsContext.events.push({
        start: function (builder) {
            builder.row(function (builder) {
                builder.text("Random Quotes are enabled.");
            });
        },
    });
}

module.onSnapMainActivityCreate = activity => {
    const randomQuote = getRandomQuote();
    longToast(randomQuote);
}

function createInterface() {
    createManagerToolBoxUI();
}

function start(_) {
    createInterface();
}

start();

im.create("settings" /* EnumUI.SETTINGS */, function (builder, args) {
    settingsContext.events.forEach(function (event) {
        event.start(builder, args);
    });
});